### PR TITLE
Add the Symfony Vardumper dd() helper method introduced in 4.1

### PR DESCRIPTION
**Pull request by antograssiot**
https://symfony.com/doc/current/components/var_dumper.html#the-dump-function

> The VarDumper component also provides a dd() ("dump and die") helper function. This function dumps the variables using dump() and immediately ends the execution of the script (using exit).
> New in version 4.1: The dd() helper method was introduced in Symfony 4.1.

### CODE REVIEW

**Comment by JakubOnderka** [comment]
Great! Can you please also add it to README ant to options?

**Comment by antograssiot** [comment]
@JakubOnderka README updated, not sure if I need to update something more...

**Comment by antograssiot** [comment]
Found out, and added it to options, I think it is all good @JakubOnderka.

**Comment by antograssiot** [comment]
any news @JakubOnderka ?

**Pull request merged**
